server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:sqlite:${user.dir}/hotel.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: never

jwt:
  secret: HotelManagementSecretKey2026ForJWTTokenGenerationAndValidation
  expiration: 86400000

logging:
  level:
    com.hotel: DEBUG